### PR TITLE
updates Amsterdam 2015 content

### PR DESCRIPTION
**Pull request by ksatirli**
* updates page titles
* updaates proposals page
* updates menu
* updates homepage

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, would you please create a PR with only your changes in it? That makes the commit history much less confusing. Thanks. (I know Kris has the same opinion which is perhaps why he didn't merge this yet either.)

**Comment by ksatirli** [comment]
I think this happened because of the rebase on upstream/master. I'll get it fixed

**Comment by ksatirli** [comment]
@bridgetkromhout done!

**Comment by bridgetkromhout** [comment]
Thanks.

**Pull request merged**
