### PR TITLE
Add Chicago 2016

### PR DESCRIPTION
**Pull request by mattstratton**

### CODE REVIEW

**Comment by geekle** [comment]
Are the sponsor ok? I see the logos, but none of them visible on the site.

**Comment by mattstratton** [comment]
@geekle there shouldn't be any sponsors? This is a "coming soon" one? it's directly from the 2016 template.

**Comment by geekle** [comment]
:+1: Cool. Just making sure :smile: 

Let me know when you're ready and I'll merge.

**Comment by bridgetkromhout** [comment]
All's well. I was just asking him (when he messaged me) to update the organizer list, and I was setting up the 2016 emails.

**Comment by geekle** [comment]
As you were then... :smiley:

**Pull request merged**
