### PR TITLE
Toronto 2015 - update local team members and add Microsoft as a sponsor.

### PR DESCRIPTION
**Pull request by WhatsChrisDoing**

### CODE REVIEW

**Comment by geekle** [comment]
@WhatsChrisDoing Andrina is still on the mailing list too. I can't see any discussion within the organizers-toronto-2015 to remove them. Is it possible to get something to confirm this?

**Comment by WhatsChrisDoing** [comment]
Sure. Steve, can you confirm for Matthew that Andrina is withdrawing from the organizing committee Matthew, we’re using Slack so most of the discussion happens there instead of email.

Chris

**Comment by stevepereira** [comment]
Sure, I spoke to Andrina last night - I hadn't realized she was still on the list but she's too busy this year to be involved.

**Comment by geekle** [comment]
Thanks @stevepereira and @WhatsChrisDoing.

**Pull request merged**
