### PR TITLE
Add portland dates

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by nibalizer** [comment]
Not Confirmed
Do Not Merge

(I either don't have permissions to add labels or can't figure out the ui))

**Comment by bridgetkromhout** [comment]
Okay. You'll need to resolve the merge conflicts before we can merge anyhow - since a lot of dates are inflight right now - but good to know. Thanks.

**Comment by BillWeiss** [comment]
I'm going to resubmit this with some more details filled in :)

**Comment by BillWeiss** [comment]
PR #2461 replaces this one.

**Comment by bridgetkromhout** [comment]
Indeed, I've merged that one.

**Pull request closed without merging**
