### PR TITLE
[dc 2015] add hotel info and CFP word cloud

### PR DESCRIPTION
**Pull request by markcornick**
closes DevOpsDaysDC/planning#22

### CODE REVIEW

**Comment by nathenharvey** [comment]
rebased this pull request so that it will merge cleanly.

**Comment by bridgetkromhout** [comment]
Hi, @nathenharvey - I don't think the rebase did what you intended. There are still tons and tons of unrelated commits in this PR. Can you and @markcornick please work together to submit a PR that's just your changes, just so it's that much easier to review? Thank you!

**Comment by nathenharvey** [comment]
yes, on it.

**Comment by nathenharvey** [comment]
closing this.  clean commit is now available.  

/cc @markcornick @bridgetkromhout

**Comment by nathenharvey** [comment]
by "closing this" I mean to say "this can be closed, but I don't have the appropriate permissions to do so"

Please feel free to close this as #1668 is a much cleaner commit of the same updates.

**Comment by bridgetkromhout** [comment]
Thanks!

**Comment by markcornick** [comment]
Closing in favor of #1668.

**Pull request closed without merging**
