### PR TITLE
googlemap: Store JS & CSS in external files

### PR DESCRIPTION
**Pull request by ctrabold**
- the file gets easier to read and maintain.
- it's easier to understand where the markers for the map are stored
`index.html` is too generic IMO (I spend a significant amount of
time to find the right place to update the map :)

Hopefully this helps other people to find their way to maintain their
events on the map as well.

I also cleaned up the indention in the JS file - ignore whitespace helps
when comparing to see that no 'real' code has been changed.

### CODE REVIEW

**Comment by ctrabold** [comment]
@bridgetkromhout This changes the way the datapoints on the google map are managed - please review :)

**Comment by bridgetkromhout** [comment]
> @bridgetkromhout This changes the way the datapoints on the google map are managed - please review :)

Thanks, @ctrabold. When I build it locally, it doesn't look quite right. Here's how it looks before your change:

screen shot 2015-10-17 at 9 47 01 pm

And here's how it looks after your change:

screen shot 2015-10-17 at 9 46 40 pm

Can you fix it so we still have the white boxes around the dates and they stay with a smaller font like they have in the old version? Thanks.

**Comment by ctrabold** [comment]
@bridgetkromhout moved the CSS link into the `header` and that fixed it. :blush: 

he labels are now shown in style:

dod_map_preview

**Comment by bridgetkromhout** [comment]
Okay, thanks!

**Pull request merged**
