### PR TITLE
Fills out Pittsburgh 2015 proposals page

### PR DESCRIPTION
**Pull request by colindean**
:hand: :no_entry_sign: :red_circle: 

This is blocked on cmluciano/blinder-dod#3.

@cmluciano or I will post here when this can be merged. Otherwise, folks will get a big ol' white page.

### CODE REVIEW

**Comment by colindean** [comment]
Might just link to it for now.

**Comment by cmluciano** [comment]
Think we should just link for now. Also our fork is in a private repo for now.

**Comment by carsomyr** [comment]
Hey all, I was out from sickness. Is there a list of stuff that still needs to be added?

**Comment by bridgetkromhout** [comment]
Hi, @colindean - I added a "do not merge" label, but since historically we don't usually have "do not merge" stuff sitting around, I can't guarantee someone won't merge it!

**Comment by colindean** [comment]
@bridgetkromhout This is now safe to merge. We're going to workaround the blocking issue by linking directly to the CFP app instead of embedding it.

**Comment by cmluciano** [comment]
👌

**Comment by bridgetkromhout** [comment]
Okay!

**Pull request merged**
