### PR TITLE
Add missing comma - duh

### PR DESCRIPTION
**Pull request by jooooooon**
Oops... missed a comma. Doh.

### CODE REVIEW

**Comment by jooooooon** [comment]
Hey @bridgetkromhout if you're still around, could you merge this one too? Sorry to nag, but I broke the site...

**Comment by jedi4ever** [comment]
done @jooooooon  ; can I come to Paris now ?

**Comment by jooooooon** [comment]
@jedi4ever Yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeees! :)))))

**Comment by bridgetkromhout** [comment]
Sorry, was in a Google hangout. Work calls. :) yay for Patrick.

**Comment by jooooooon** [comment]
No worries @bridgetkromhout, my fault for breaking it in the first place.

**Comment by bridgetkromhout** [comment]
And mine for merging hastily on my phone while walking through an airport. :)

**Pull request merged**
