### PR TITLE
Adds Pittsburgh 2015 organizers' twitters to contact info

### PR DESCRIPTION
**Pull request by colindean**
Unless there are nays from 

@cmluciano
@littleidea
@carsomyr
@meatballhat
@sethvargo

### CODE REVIEW

**Comment by sethvargo** [comment]
:-1:

**Comment by bridgetkromhout** [comment]
Looks like @sethvargo is objecting - I can't tell if in whole or in specific part - I'm marking this as `do not merge` until you folks sort out what you want.

**Comment by sethvargo** [comment]
Sorry. That was supposed to be a :+1:. Idk why, but sometimes if you type the +1 really fast, it comes out as a -1 :frowning:. :+1:

**Comment by carsomyr** [comment]
@bridgetkromhout Looks good!

**Pull request merged**
