### PR TITLE
[dc 2015] fix sponsorship table

### PR DESCRIPTION
**Pull request by markcornick**
My CSS clashed with the default CSS, leaving the sponsorship table
empty. This should fix it :)

### CODE REVIEW

**Comment by markcornick** [comment]
Can you hold on merging this for the moment? I may need to make one more fix. :neutral_face:

**Comment by bridgetkromhout** [comment]
That's what I get for merging from my phone without testing. :)

**Comment by markcornick** [comment]
Well, that's what _I_ get for not running my code through web first. Turns out the markdown filter in that page was eating the inline CSS. (Is this a blameless post-mortem? :)

Anyway, this should be good to merge now. Thanks for your patience!

**Comment by bridgetkromhout** [comment]
> (Is this a blameless post-mortem? :)

The only kind!

**Pull request merged**
