### PR TITLE
updates content for AMS 2015

### PR DESCRIPTION
**Pull request by ksatirli**

### CODE REVIEW

**Comment by KrisBuytaert** [comment]
Kerim,  can you rebase first ?

**Comment by bridgetkromhout** [comment]
Kerim, when you revise this, can you ensure you are only changing relevant lines? The diffs are much less readable if you or your editor are making white space changes throughout a file. Thanks.

**Comment by ksatirli** [comment]
@KrisBuytaert: done; I did not notice beforehand that my branch was out-of-sync with upstream/master. Fixed now.

@bridgetkromhout a misconfig in my editor - thanks, it should be fixed now.

**Comment by bridgetkromhout** [comment]
Hi, @ksatirli - thanks! Can you also fix your editor so it stops stripping newlines from the ends of files? http://robots.thoughtbot.com/no-newline-at-end-of-file has more info on that. That introduces unneeded changes and makes the diff less readable too.

Also, your global team file is out of date. Can you look at the ones in the other current 2015 events? https://github.com/jedi4ever/devopsdays-webby/blob/master/site/content/events/2015-paris/_team_global.txt for example. Thanks.

**Comment by ksatirli** [comment]
@bridgetkromhout thanks for the head's up - we based our branch off of the 2014 edition of Amsterdam, hence the team file content mismatch. 

I'm wondering if we can move the global team file to the root level and tag them by year maybe? That way, all local events would always have the same global team members for that year and we'd have less duplicate information and mismatching. It could be, however, that you have a reason for making the global team "local", which I'm not aware of. Glad to take part in the discussion, if needed.

As far as the newlines go, I've updated my PR. It would be great to have something like [EditorConfig](http://editorconfig.org/) so that all compatible editors can understand the standard we want to work with.

**Comment by bridgetkromhout** [comment]
> we based our branch off of the 2014 edition of Amsterdam

That explains why you didn't add your event to the footer (this is new) - could you do that too, please? Then we can get this merged.
https://github.com/jedi4ever/devopsdays-webby/blob/master/site/content/_future.txt

> I'm wondering if we can move the global team file to the root level and tag them by year maybe? 

I'd like to do that - just haven't put the time in to implement it yet.

PRs welcome on editor config guidelines - I haven't put time into that since it's not usually a problem (until it is!)

**Comment by ksatirli** [comment]
Alright - updated the future file, too!

I'll see if I can send in a PR for editor config - need to figure out what was decided upon (other than newlines)

**Comment by bridgetkromhout** [comment]
Sorry, didn't have time to pull this down and check it until now.

This commit looks good and I'll merge it, but you should update the "program" page because "Please see <strong><a href="http://lanyrd.com/2014/devopsams/">Lanyrd</a></strong> for the latest program updates!<br />" is outdated. Thanks.

**Comment by ksatirli** [comment]
@bridgetkromhout thanks for merging. I have updated the program page in a separate PR

**Pull request merged**
