### PR TITLE
Adds Girl Develop It to Pittsburgh 2015 media sponsors

### PR DESCRIPTION
**Pull request by colindean**
Eh, @rachelthompson and @melancholyfleur?

@j41manning @sethvargo @meatballhat @cmluciano @carsomyr

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1: although I think we can imageoptim that logo

**Comment by phrawzty** [comment]
> although I think we can imageoptim that logo

Waiting to merge until this is either acted on or dismissed.

**Comment by melancholyfleur** [comment]
:+1: when the thing above is addressed.

**Comment by colindean** [comment]
I'll get around to it tonight.

**Comment by sethvargo** [comment]
@phrawzty let's just merge this as-is, and I'll sweep all the images in one pass

**Pull request merged**
