### PR TITLE
Change to Amsterdam 2015 index.

### PR DESCRIPTION
**Pull request by ildiroen**
Removed mention of early bird tickets (sold out!) and mentioning that CFP has ended. :tada:

### CODE REVIEW

**Comment by ildiroen** [comment]
Various fixes while I was busy with it anyway. :) Should be all good now.

**Comment by bridgetkromhout** [comment]
Hi, @ildiroen - want to fix the merge conflict so we can merge this? Thanks!

**Comment by ildiroen** [comment]
@bridgetkromhout @KrisBuytaert Will make sure to do that either tonight or tomorrow. :) Have some more changes to add anyway and I'm a bit burnt out today.

**Comment by bridgetkromhout** [comment]
Sounds good.

**Pull request closed without merging**
