### PR TITLE
Adds Pittsburgh 2015 sponsors up to current

### PR DESCRIPTION
**Pull request by colindean**
This is up to current as of this afternoon.

@justinxreese please verify.

Also, I cannot actually get webby's deps to install on my machine, so I'm not entirely certain that this works.

### CODE REVIEW

**Comment by justinxreese** [comment]
That looks like an old Apcera logo to me. I've attached the one they gave me for Code & Supply's sponsorship.

apcera-logo-dark-b6adc5649d81d077667bd496f89c1ec3

**Comment by justinxreese** [comment]
Otherwise looks good. Assuming good faith that all of the sponsors send their checks soon (not going to name names since this is a public repo)

**Comment by colindean** [comment]
Yeah, I pulled it from last year's. I'll update it.

**Comment by colindean** [comment]
Ready.

**Pull request merged**
