### PR TITLE
add Chicago prospectus and event date

### PR DESCRIPTION
**Pull request by lanyonm**

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Yay! You've got a date - add yourself to the map too!

**Comment by bridgetkromhout** [comment]
Specifics are listed on http://www.devopsdays.org/pages/organizing/#3 - please add Chicago to the list above the map and add it to the map if you get a chance before I do. (Flight's about to land, so I can't right this minute.) Then this LGTM. :+1:

**Comment by lanyonm** [comment]
Thanks! Either another member of the team will make the update this morning, or I'll make it later this afternoon. The States are getting pretty packed.  :smile:

**Comment by bridgetkromhout** [comment]
Sounds good. And I should have really merged this in anyhow. I'll do that now so it's earier for someone else to edit it.

**Pull request merged**
