### PR TITLE
Dates and location for New York 2016

### PR DESCRIPTION
**Pull request by kdaniels**
Dates and location for New York 2016

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I merged this and found when I tested it locally that it's not rendering:

```
       create  output/events/2016-newyork/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""
       create  output/events/2016-newyork/code-of-conduct/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/code-of-conduct/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""
       create  output/events/2016-newyork/contact/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/contact/index.html'
[23:05:36] ERROR: erb filter error: "could not find partial '//_team_local'"
       create  output/events/2016-newyork/location/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/location/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""
       update  output/events/2016-newyork/program/ignites.html
       create  output/events/2016-newyork/program/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/program/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""
       create  output/events/2016-newyork/propose/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/propose/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""
       update  output/events/2016-newyork/registration/index.html
       create  output/events/2016-newyork/sponsor/index.html
[23:05:36] ERROR: while rendering page 'content/events/2016-newyork/sponsor/index.html'
[23:05:36] ERROR: erb filter error: "erb filter error: \"undefined method `empty?' for nil:NilClass\""

```

It's pretty late so I'll look more tomorrow. The weird thing is that this is basically a clone of 2015 and when I replaced the index.html with the exact one from 2015, it still had the same build failure.

**Comment by bridgetkromhout** [comment]
Fixed.

**Comment by kdaniels** [comment]
Thank you! What turned out to be the issue with the erb?

**Comment by bridgetkromhout** [comment]
> Thank you! What turned out to be the issue with the erb?

You can see the fun here:
https://github.com/jedi4ever/devopsdays-webby/pull/2476

**Pull request merged**
