### PR TITLE
Toronto 2015 - Add happy hour details.

### PR DESCRIPTION
**Pull request by WhatsChrisDoing**

### CODE REVIEW

**Comment by WhatsChrisDoing** [comment]
I've add some more program updates. Could this get merged today please.

**Comment by WhatsChrisDoing** [comment]
Thank you

**Comment by bridgetkromhout** [comment]
:+1:  Hey Chris, if we're ever super-slow to merge, feel free to ping me on Twitter. I use github for work too, so I sometimes miss personal notifications. (I saw you emailed, but email, well. You know.)

**Comment by WhatsChrisDoing** [comment]
Excellent. I’ll do that. We’re getting down to the wire so I’m sure we’ll have a few more updates.

Chris

**Pull request merged**
