### PR TITLE
Initial Toronto 2015 site.

### PR DESCRIPTION
**Pull request by WhatsChrisDoing**
This is the skeleton site for DevOpsDays Toronto 2015.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi -can you also add Toronto to the map on the front page since you have a specific date? And please check the other current devopsdays because you have an old list of core organizers. Thanks.

**Comment by WhatsChrisDoing** [comment]
Hi Bridget, I've made the changes. Chris

**Comment by WhatsChrisDoing** [comment]
I may have totally messed this up. Total git newbie with my first pull request. I was trying to sync my fork with the master and I'm not sure I wanted to do that. It's fairly straight forward for me to recreate everything if necessarily.

**Comment by bridgetkromhout** [comment]
> I may have totally messed this up. Total git newbie with my first pull request. I was trying to sync my fork with the master and I'm not sure I wanted to do that. It's fairly straight forward for me to recreate everything if necessarily.

All is well. Next time it will be less confusing if you do `git pull upstream master; git push` before you start making changes.

**Pull request merged**
