### PR TITLE
[DC 2016] add JHC Technology to sponsors

### PR DESCRIPTION
**Pull request by markcornick**

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Please submit a matching PR to https://github.com/devopsdays/devopsdays-web/pulls - thanks.

**Comment by markcornick** [comment]
Will do - should future PRs go to that repo only, or both?

**Comment by bridgetkromhout** [comment]
We're cutting over at the end of this week. If you can migrate your own site then it will be the way you want it. :)

**Comment by markcornick** [comment]
Thanks. I'm working on the migration to the new site in https://github.com/devopsdaysdc/devopsdays-web/tree/dc-2016-migration. It looks like we have some Very Special Blossom issues to figure out...

**Pull request merged**
