### PR TITLE
Added new talks for devopsdays 2015.

### PR DESCRIPTION
**Pull request by ildiroen**
Seems like my commit history got a little bit dirty, but it should be good. :)

### CODE REVIEW

**Comment by phrawzty** [comment]
The content looks good, but it'd be nice if you would squash the commit list down a bit. Thanks! :cake:

**Comment by ildiroen** [comment]
Hey Dan,

I can't really seem to get this squished together properly. Any tips?

**Comment by phrawzty** [comment]
An interactive rebase where you just `fixup` (or `squash`, as you like) should do the trick. 

Try this:
```
$ git rebase -i HEAD~13
```
That should open your editor with the last 13 commits listed - you can fold them down into some reasonable number from there.

**Comment by ildiroen** [comment]
Closing this pull request as I've added a clean one instead.

**Pull request closed without merging**
