### PR TITLE
Sets Pittsburgh 2015 CFP dates

### PR DESCRIPTION
**Pull request by colindean**
Don't merge until two of these people post agreement:

@cmluciano
@meatballhat
@sethvargo
@carsomyr
@littleidea

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1:

**Comment by littleidea** [comment]
works but I would plan on a soft close

**Comment by KrisBuytaert** [comment]
I count Seth and Andrew so thats  3 people agreeing  ..

**Comment by carsomyr** [comment]
Looks good? Thanks!

**Pull request merged**
